version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: miarchivo_db
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'
      SA_PASSWORD: 'YourStrong!Passw0rd'
      MSSQL_TCP_PORT: '1433'
    ports:
      - '1433:1433'
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1'
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: miarchivo_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_SERVER: db
      DB_NAME: MyArchivo
      DB_USER: sa
      DB_PASSWORD: YourStrong!Passw0rd
      PORT: 4001
    ports:
      - '4001:4001'
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: miarchivo_frontend
    depends_on:
      - backend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
